---
title: 'Lab assignment 1: Processing models'
author: "Luka van der Plas (4119142) & Rianne Lam (6888216)"
date: "15 november 2019"
output:
  html_document:
    df_print: paged
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Section I: Human data

### Question 1:

A.

```{r, echo = FALSE}
load("keyPressDataWithLaneDeviation.Rdata")
  
NoErr <- subset(keyPressDataWithLaneDeviation, typingErrorMadeOnTrial == 0)
totalDialingTime <- subset(NoErr, phoneNrLengthAfterKeyPress == 11)

summaryStatistics <- function(data) {
  meanCond <- mean(data)
  sdCond <- sd(data)
  seCond <- sdCond / sqrt(12)
  return(c(meanCond, sdCond, seCond))
}

summarizeData <- function(dataToSummarize) {

totalDialingTimePP <- aggregate(dataToSummarize[ , c("pp", "timeRelativeToTrialStart")], by = list(dataToSummarize$pp), FUN = mean)$timeRelativeToTrialStart

summary <- summaryStatistics(totalDialingTimePP)

return(summary)
} 
  
summaryDataCond1 <- summarizeData(subset(totalDialingTime, partOfExperiment == "dualSteerFocus"))
summaryDataCond2 <- summarizeData(subset(totalDialingTime, partOfExperiment == "dualDialFocus"))

results <- data.frame("M" = paste(round(c(summaryDataCond1[1], summaryDataCond2[1]), 3),  " ms"),
                   "SD" = paste(round(c(summaryDataCond1[2], summaryDataCond2[2]), 3),  " ms"),
                   "SE" = paste(round(c(summaryDataCond1[3], summaryDataCond2[3]), 3),  " ms"))
rownames(results) <- c("Steering focus", "Dialing focus")

results

```

B.

```{r, echo = FALSE}

avg_dev_trial <- function(data, trialN) {
  dataTrial <- subset(data, data$trial == trialN)
  abs_lane_pos <- mean(abs(dataTrial$lanePosition), na.rm = TRUE)
  return(abs_lane_pos)
}

avg_dev_cond <- function(condition) {
  dataCond <- subset(NoErr, NoErr$partOfExperiment == condition) 
  ppCount <- max(dataCond$pp)
  abs_lane_pos <- vector()
  for (i in 1:ppCount) {
      dataCondpp <- subset(dataCond, dataCond$pp == i)
      trials <- unique(dataCondpp$trial)
    for (j in trials) {
      mean_abs_lane_pos <- avg_dev_trial(dataCondpp, j)
      abs_lane_pos <- append(abs_lane_pos, mean_abs_lane_pos)
    }
  }
  
  return(summaryStatistics(abs_lane_pos))
} 

steerFocus <- avg_dev_cond("dualSteerFocus")
dialFocus <- avg_dev_cond("dualDialFocus")

results <- data.frame("M" = paste(round(c(steerFocus[1], dialFocus[1]), 3),  " m"),
                   "SD" = paste(round(c(steerFocus[2], dialFocus[2]), 3),  " m"),
                   "SE" = paste(round(c(steerFocus[3], dialFocus[3]), 3),  " m"))
rownames(results) <- c("Steering focus", "Dialing focus")

results


```

C.

```{r, echo = FALSE}

library(ggplot2)
library(dplyr)

mean_dev_pp_df <- NoErr %>%
  # Group by participant, keypress, condition
  group_by(pp, phoneNrLengthAfterKeyPress, partOfExperiment) %>%  
  # Take the mean of absolute lane position for these groups
  summarise(mean_dev_pp = mean(abs(lanePosition)))

mean_dev_all <- mean_dev_pp_df %>%
  # Group by keypress, condition
  group_by(phoneNrLengthAfterKeyPress, partOfExperiment) %>%
  # Take the mean of the mean for these groups per participant (mean across participants)
  summarise(mean_dev = mean(mean_dev_pp)) %>%
  # Only look at the two relevant conditions
  filter(partOfExperiment %in% c("dualDialFocus", "dualSteerFocus")) 

# Replace condition names for plot
mean_dev_all$partOfExperiment <- recode(mean_dev_all$partOfExperiment, "dualDialFocus" = "Dialing-focus", "dualSteerFocus" = "Steering-focus")

mean_dev_all

n <- max(unique(keyPressDataWithLaneDeviation$pp))

ggplot(mean_dev_all, aes(x = phoneNrLengthAfterKeyPress, y = mean_dev, group = partOfExperiment)) +
  geom_line(size = 1) +
  geom_point(aes(shape = factor(partOfExperiment)), size = 3.5) +
  theme_classic() +
  theme(legend.position = c(0.9, 0.1), legend.title = element_blank()) + 
  ylab("Lateral Deviation (m)") + 
  xlab("Number of key presses") + 
  geom_errorbar(aes(ymin = mean_dev - (sd(mean_dev) / sqrt(n)), ymax = mean_dev + (sd(mean_dev) / sqrt(n))), size = 1, width = 0.2, position = position_dodge(0.05)) 
  # scale_x_continuous(breaks = seq(0, 12, 2)) +
  # scale_y_continuous(breaks = seq(0, 0.8, 0.2))

```




```

D. 




